inital script commit
AmitBEL/WordEquationsToText pull request #1
Opened 2021-04-27 16:56 UTC by AmitBEL

2021-04-27 17:45 UTC, Moshikolev requested changes

2021-04-27 17:45 UTC, Moshikolev commented on change_all_equations_to_text.py
> +# print(sys.argv[1])
please remove all of the unessery comments.

2021-04-27 17:45 UTC, Moshikolev commented on change_all_equations_to_text.py
> +# equations_to_text(xml_file_path1, new_xml_file_path1)
please remove.

2021-04-27 17:45 UTC, Moshikolev commented on change_all_equations_to_text.py
> +docx_file_path1 = os.path.normpath(orig_docx_file_path1)
r'asdasdas/asdasd/asdasd'

2021-04-27 17:45 UTC, Moshikolev commented on change_all_equations_to_text.py
> +orig_docx_file_path1 = sys.argv[1]
change to original

2021-04-27 17:45 UTC, Moshikolev commented on change_all_equations_to_text.py
> +orig_docx_file_path1 = sys.argv[1]
ORIGINAL_DOCX_PATH_INDEX = 1

2021-04-27 17:45 UTC, Moshikolev commented on change_all_equations_to_text.py
> +
Add comments here about the logic of the function
1. getting the docx file
2. extracting to zop
3. etc ...

2021-04-27 17:45 UTC, Moshikolev commented on change_all_equations_to_text.py
> +def zip_file(zip_file_path, directory):
please add to all functions parameters an '_'

2021-04-27 17:45 UTC, Moshikolev commented on change_all_equations_to_text.py
> +tmp_document_xml_file_path1 = extract_directory1 + 'word/document1.xml'
remove the file from the names

2021-04-27 17:45 UTC, Moshikolev commented on change_all_equations_to_text.py
> +zip_file(zip_file_path1, extract_directory1)
extract_directory => please think on a better name

2021-04-27 17:45 UTC, Moshikolev commented on change_all_equations_to_text.py
> +new_docx_file_path1 = zip_to_docx(zip_file_path1)
new_docx_file_path1 => result_docx_path

2021-04-27 17:45 UTC, Moshikolev commented on change_all_equations_to_text.py
> +shutil.rmtree(extract_directory1)
please add a comment explaining what this line does

2021-04-27 17:45 UTC, Moshikolev commented on change_all_equations_to_text.py
> +    zip_file_path = docx_file_path[0:-4] + "zip"
please add comments on what the function does 
"""

2021-04-27 17:45 UTC, Moshikolev commented on change_all_equations_to_text.py
> +    new_docx_file_path = docx_file_path + '_copy'
please add to the comment that you are creating a new file to preserve the original one

2021-04-27 17:45 UTC, Moshikolev commented on change_all_equations_to_text.py
> +    new_docx_file_path = docx_file_path + '_copy'
new_docx_file_path => duplicated_docx_path

2021-04-27 17:45 UTC, Moshikolev commented on change_all_equations_to_text.py
> +    zip_file_path = docx_file_path[0:-4] + "zip"
please try to copy the file directly to the zip path

2021-04-27 17:45 UTC, Moshikolev commented on change_all_equations_to_text.py
> +        extract_directory = zip_file_path[0:-4] + '/'
extracted_directory_path

2021-04-27 17:45 UTC, Moshikolev commented on change_all_equations_to_text.py
> +
replace_file_suffix(suffix_length,new_suffix)
replace_file_suffix(suffix_length=4,new_suffix="zip")

2021-04-27 17:45 UTC, Moshikolev commented on change_all_equations_to_text.py
> +def equations_to_text(document_xml_file_path, out_xml_file_path):
document_xml_path

2021-04-27 17:45 UTC, Moshikolev commented on change_all_equations_to_text.py
> +        with open(out_xml_file_path, "wt", encoding="utf8") as fout:
please check what is this t

2021-04-27 17:45 UTC, Moshikolev commented on change_all_equations_to_text.py
> +def zip_file(zip_file_path, directory):
create_zip_file

2021-04-27 17:45 UTC, Moshikolev commented on change_all_equations_to_text.py
> +                zipObj.write(file_path, p.relative_to(directory))
please add comment about the relative

2021-04-27 17:45 UTC, Moshikolev commented on change_all_equations_to_text.py
> +    # copyfile(docx_file_path, zip_file_path)
please remove

2021-04-28 09:17 UTC, AmitBEL commented on change_all_equations_to_text.py
> +        with open(out_xml_file_path, "wt", encoding="utf8") as fout:
Open in text mode.

2021-04-28 15:13 UTC, Moshikolev requested changes

2021-04-28 15:13 UTC, Moshikolev commented on change_all_equations_to_text.py
> +    :param new_suffix:      the new suffix to be added to path
add underscore

2021-04-28 15:13 UTC, Moshikolev commented on change_all_equations_to_text.py
> +        # _extraction_directory = _zip_path[0:-4] + '/'
please remove.

2021-04-28 15:14 UTC, Moshikolev commented on change_all_equations_to_text.py
> +        # _extraction_directory = _zip_path[0:-4] + '/'
Please add a few words in the readme file

2021-04-28 15:22 UTC, Moshikolev approved these changes

2021-04-28 15:22 UTC, merged